pool:
  vmImage: 'macOS-10.14'

steps:

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Identities.p12'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '36ec1bf8-357b-439f-b1bb-0faacea2f5ce.HiOSStuart.mobileprovision'

- script:
    bundle install
    bundle exec fastlane build ios
  displayName: Run Fastlane

- task: CopyFiles@1
  inputs:
    SourceFolder: '/'
    Contents: 'HelloiOS.ipa'
    TargetFolder: '$(build.artifactStagingDirectory)/'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/HelloiOS.ipa'
    ArtifactName: 'HelloiOS.ipa'
    publishLocation: 'Container'